Update twitter2mastodon.yml

diff --git a/.github/workflows/twitter2mastodon.yml b/.github/workflows/twitter2mastodon.yml
--- a/.github/workflows/twitter2mastodon.yml
+++ b/.github/workflows/twitter2mastodon.yml
@@ -1,7 +1,10 @@
 name: Twitter to Mastodon Bot
 
 on:
-  workflow_dispatch: # Manuelle Ausführung
+  schedule:
+    - cron: '0 6 * * *'    # Einmal täglich um 06:00 Uhr
+    - cron: '0 13-22 * * *' # Stündlich von 13:00 bis 22:00 Uhr
+  workflow_dispatch:        # Manuelle Ausführung
 
 jobs:
   run-twitter-to-mastodon:
@@ -32,12 +35,12 @@ jobs:
           python -m pip install --upgrade pip
           pip install -r requirements.txt
 
-      - name: Run Twitter to Mastodon Script with Debug
+      - name: Run Twitter to Mastodon Script
         env:
           MASTODON_API_URL: ${{ secrets.MASTODON_API_URL }}
           MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
           TWITTER_URL: ${{ secrets.TWITTER_URL }}
           HASHTAGS: ${{ secrets.HASHTAGS }}
         run: |
-          echo "Starting the script with debug outputs..."
-          python twitter2mastodon.py || echo "Script execution failed. Check debug logs above for details."
+          echo "Starting the script..."
+          python twitter2mastodon.py || echo "Script execution failed. Check logs above for details."
